edit_spot/urls.py
from django.conf.urls import *
from rest_framework.routers import DefaultRouter

from edit_spot import views, classviews
from miroutes.model_choices import GRADE_CHOICES, AID_GRADE_CHOICES

from django.http import HttpResponse, JsonResponse
from rest_framework.routers import DefaultRouter

app_name = 'edit_spot'

do_nothing = lambda *args, **kwargs: HttpResponse()

route_geom_router = DefaultRouter()
route_geom_router.register(r'routegeometries', classviews.RouteGeometryViewSet, basename='routegeometry')

urlpatterns = [
url(r'^wall_img(?P<tiler_id>\d+)/edit$', views.edit_wall_img, name='edit_wall_img'),
url(r'^wall_img(?P<tiler_id>\d+)/revert(?P<version_id>\d+)$', views.revert_wall_img, name='revert_wall_img'),
url(r'^add_wall_img$', views.add_wall_img, name='add_wall_img'),
url(r'^add_wall_from_pano/(?P<pano_id>\d+)$', views.add_wall_from_pano, name='add_wall_from_pano'),

url(r'^wall_img(?P<tiler_id>\d+)/add_wall$', views.add_wall, name='add_wall'),
url(r'^wall(?P<wall_id>\d+)/routelist_chunk$', views.routelist_chunk, name='routelist_chunk'),

url(r'^edit_route/$', do_nothing, name='edit_route_noid'),
url(r'^edit_route/(?P<route_id>\d+)$', views.edit_route, name='edit_route'),
url(r'^deprecate_route/(?P<route_id>\d+)$', views.deprecate_route, name='deprecate_route'),
url(r'^deprecate_route/$', views.deprecate_route, name='deprecate_route'),
url(r'^route(?P<route_id>\d+)/add_material$', views.add_material, name='add_material'),
url(r'^route(?P<route_id>\d+)/link_materials$', views.link_materials, name='link_materials'),
url(r'^route(?P<route_id>\d+)/toggle_link_material/(?P<material_id>\d+)$', views.toggle_link_material, name='toggle_link_material'),
url(r'^route(?P<route_id>\d+)/toggle_link_material/$', do_nothing, name='toggle_link_material'),

url(r'^add_route$', views.add_route, name='add_route'),
url(r'^revert_route/route(?P<route_id>\d+)/version(?P<version_id>\d+)$', views.revert_route, name='revert_route'),
url(r'^revert_wall/wall(?P<wall_id>\d+)/version(?P<version_id>\d+)$', views.revert_wall, name='revert_wall'),

url(r'^wall(?P<wall_id>\d+)/edit_wall$', views.edit_wall, name='edit_wall'),
url(r'^wall(?P<wall_id>\d+)/del_wall$', views.del_wall, name='del_wall'),

url(r'^wallview(?P<wall_id>\d+)/link_routes$', views.link_routes, name='link_routes'),
url(r'^wallview(?P<wallview_id>\d+)/toggle_link_route/(?P<route_id>\d+)$', views.toggle_link_route, name='toggle_link_route'),
url(r'^wallview(?P<wallview_id>\d+)/toggle_link_route/$', do_nothing, name='toggle_link_route_noid'),
url(r'^wallview(?P<wallview_id>\d+)/store_geojson$', views.store_geojson, name='store_geojson'),
url(r'^wallview(?P<wallview_id>\d+)/edit_gym_route$', views.edit_gym_route, name='edit_gym_route'),
url(r'^wallview(?P<wallview_id>\d+)/edit_gym_route(?P<route_id>\d+)$', views.edit_gym_route, name='edit_gym_route'),
url(r'^changeset/(?P<wallview1_id>\d+)/(?P<wallview2_id>\d+)$', views.wallview_changeset, name='wallview_changeset'),

url(r'^wall(?P<wall_id>\d+)/link_materials$', views.link_materials, name='link_materials'),
url(r'^wall(?P<wall_id>\d+)/toggle_link_material/(?P<material_id>\d+)$', views.toggle_link_material, name='toggle_link_material'),
url(r'^wall(?P<wall_id>\d+)/toggle_link_material/$', do_nothing, name='toggle_link_material'),
url(r'^wall(?P<wall_id>\d+)/add_material$', views.add_material, name='add_material'),

url(r'^wall(?P<wall_id>\d+)/draw_routes$', views.draw_routes, name='draw_routes'),
url(r'^wall(?P<wall_id>\d+)/publish_wall$', views.publish_wall, name='publish_wall'),
url(r'^wall(?P<wall_id>\d+)/reset_dev_wall$', views.reset_dev_wall, name='reset_dev_wall'),

url(r'^wall(?P<wall_id>\d+)/decorate_wall$', views.decorate_wall, name='decorate_wall'),
url(r'^wall(?P<wall_id>\d+)/finish_wall_edit$', views.finish_wall_edit, name='finish_wall_edit'),
url(r'^wall(?P<wall_id>\d+)/delete$', views.delete_wall, name='delete_wall'),

url(r'^wall_img(?P<tiler_id>\d+)/rotate_right$', views.rotate_wall_img_right, name='rotate_img_right'),
url(r'^wall_img(?P<tiler_id>\d+)/rotate_left$', views.rotate_wall_img_left, name='rotate_img_left'),

url(r'^routegeometry(?P<geom_id>\d+)/delete$', views.del_geom, name='del_geom'),
url(r'^rest/tiler/(?P<pk>[0-9]+)/$', classviews.TilerDetail.as_view(), name='get_tiler'),

url(r'^grades_table$', lambda *args, **kwargs:JsonResponse(GRADE_CHOICES, safe=False), name='grades_table'),
url(r'^aid_grades_table$', lambda *args, **kwargs:JsonResponse(AID_GRADE_CHOICES, safe=False), name='aid_grades_table')
]

urlpatterns += route_geom_router.urls

miroutes/urls.py
from django.conf.urls import *
from rest_framework.routers import DefaultRouter

from miroutes import views
from miroutes import classviews
from django.http import HttpResponse
do_nothing = lambda *args, **kwargs: HttpResponse()

app_name = 'miroutes'

route_router = DefaultRouter()
route_router.register(r'rest/routes', classviews.RouteViewSet, basename='rest-route')

urlpatterns = [ url(r'^$', views.index, name='index'),
url(r'^search/', views.search, name='search'),
url(r'^about/', views.about, name='about'),
url(r'^imprint/', views.imprint, name='imprint'),
url(r'^license/(?P<license_key>[0-9a-z-]+)$', views.license, name='license'),
url(r'^privacy/', views.privacy, name='privacy'),
url(r'^news/', views.news, name='news'),
url(r'^help/', views.help, name='help'),
url(r'^wall_selection/', views.wall_selection, name='wall_selection'),
url(r'^check_wallview_updates/(?P<since>\d+)$', views.check_wallview_updates, name='check_wallview_updates'),

url(r'^pic(?P<userpic_id>\d+)/$', views.userpic, name='userpic'),
url(r'^pic(?P<userpic_id>\d+)/edit$', views.userpic_edit, name='userpic_edit'),
url(r'^pic$', do_nothing, name='userpic_stub'),
url(r'^picdel(?P<userpic_id>\d+)$', views.del_userpic, name='del_userpic'),
url(r'^picdel$', do_nothing, name='del_userpic_noid'),

url(r'^wall(?P<wall_id>\d+)/add_userpic', views.add_userpic, name='add_userpic'),
url(r'^route(?P<route_id>\d+)/add_userpic', views.add_userpic, name='add_userpic'),
url(r'^wall(?P<wall_id>\d+)/userpic_display$', views.userpic_display, name='userpic_display'),
url(r'^route(?P<route_id>\d+)/userpic_display$', views.userpic_display, name='userpic_display'),
url(r'^wall(?P<wall_id>\d+)/userpics', views.show_userpics, name='show_userpics'),
url(r'^route(?P<route_id>\d+)/userpics', views.show_userpics, name='show_userpics'),

url(r'^wall(?P<wall_id>\d+)/show_on_map', views.wall_on_map, name='wall_on_map'),
url(r'^wall(?P<wall_id>\d+)/dev$', views.wall_detail_dev, name='wall_detail_dev'),
url(r'^wall(?P<wall_id>\d+)/$', views.wall_detail, name='wall_detail'),
url(r'^wall(?P<wall_id>\d+)/just-published$', lambda *args, **kwargs:views.wall_detail(*args, **kwargs, just_published=True), name='wall_detail_published'),
url(r'^wall$', do_nothing, name='wall_detail_stub'),
url(r'^wall(?P<wall_id>\d+)/route_histogram$', views.wall_route_histogram, name='wall_route_histogram'),
url(r'^wall(?P<wall_id>\d+)/popup$', views.wall_popup, name='wall_popup'),
url(r'^wall(?P<wall_id>\d+)/routes$', views.wall_routelist, name='wall_routelist'),
url(r'^wall(?P<wall_id>\d+)/viewed$', views.wall_viewed, name='wall_viewed'),
url(r'^wall(?P<wall_id>\d+)/addfav$', views.wall_toggle_favourite, name='wall_toggle_favourite'),
url(r'^rest/wall/(?P<pk>\d+)$', classviews.RestWall.as_view(), name='rest_wall'),
url(r'^rest/news$', classviews.NewsViewSet.as_view(), name='rest_news'),
url(r'^rest/wall_activity/(?P<wall_id>\d+)$', classviews.RestWallActivity.as_view(), name='rest_wall_activity'),

url(r'^route(?P<route_id>\d+)$', views.route_detail, name='route_detail'),
url(r'^route$', do_nothing, name='route_detail_stub'),
url(r'^rest/route_activity/(?P<route_id>\d+)$', classviews.RestRouteActivity.as_view(), name='rest_route_activity'),
url(r'^route/short_info(?P<route_id>\d+)$', views.route_short_info, name='route_short_info'),
url(r'^route/short_info$', views.route_short_info, name='route_short_info'),
url(r'^route(?P<route_id>\d+)/timeline_chunk$', views.route_timeline_chunk, name='route_timeline_chunk'),
url(r'^route(?P<route_id>\d+)/qrcode$', views.route_qrcode, name='route_qrcode'),
url(r'^tick_route/(?P<route_id>\d+)$', views.tick_route, name='tick_route'),
url(r'^tick_route/$', views.tick_route, name='tick_route'),

url(r'^ticked/(?P<route_id>\d+)$', views.add_ascent, name='add_ascent'),
url(r'^ticked/$', views.add_ascent, name='add_ascent'),
url(r'^save_mapview$', views.save_mapview, name='save_mapview'),
url(r'^save_baselayer$', views.save_baselayer, name='save_baselayer'),
url(r'^ascent/details(?P<ascent_id>\d+)$', views.ascent_details, name='ascent_details'),
url(r'^ascent/details$', views.ascent_details, name='ascent_details'),
url(r'^ascent/delete(?P<ascent_id>\d+)$', views.del_ascent, name='del_ascent'),
url(r'^ascent/delete$', views.del_ascent, name='del_ascent'),

url(r'toggle_show_inactive', views.toggle_show_inactive, name='toggle_show_inactive'),
url(r'^filter_labels/$', do_nothing, name='filter_labels_ng'),
url(r'^filter_labels/(?P<grade_system>\d)$', views.get_filter_labels, name='filter_labels'),
]

urlpatterns += route_router.urls


from django.contrib.sitemaps.views import sitemap
from miroutes.sitemaps import sitemaps
from django.urls import path
from django.views.decorators.cache import cache_page

urlpatterns += [path('sitemap.xml', cache_page(60 * 60 * 24)(sitemap), {
    'sitemaps': sitemaps,
    'template_name': 'sitemap/MiroutesSitemap.html',},
    name='sitemap'), ]

mitopo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import *
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from rest_framework_swagger.views import get_swagger_view

from mitopo.views import schema_view, greeter_index

app_name = 'mitopo'

urlpatterns = [
    path(r'robots.txt', TemplateView.as_view(template_name='mitopo/robots.txt', content_type='text/plain')),
    path(r'admin/', admin.site.urls),
    path("soc/", include("social_django.urls", namespace="social")),
    path(r'i18n/', include('django.conf.urls.i18n')),
    path(r'micomments/', include('micomments.urls')),
    path(r'upload/', include('django_file_form.urls')),
    url(r'apidoc/', schema_view)
]

urlpatterns += i18n_patterns(
    path('', greeter_index, name='greeter_index'),
    path('miroutes/', include('miroutes.urls')),
    path('edit_spot/', include('edit_spot.urls')),
    path('generic_markers/', include('generic_markers.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('stitcher/', include('stitcher.urls')),
    path('micontactform/', include('micontactform.urls')),
    path('miexport/', include('miexport.urls')),
    path('postbox/', include('postbox.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

)

# if in debug mode, redirect static requests to media_ROOT
from django.conf import settings
from  django.views import static

if settings.DEBUG == True:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }), ]

users/urls.py
from django.conf.urls import *
from django.contrib.auth.views import LoginView, LogoutView

from users import views
from users import classviews

from django.http import HttpResponse
do_nothing = lambda *args, **kwargs: HttpResponse()

app_name='users'

urlpatterns = [
    url(r'^profile', views.profile, name='profile'),
    url(r'^activityfeed/(?P<user_id>\d+)', views.activityfeed, name='activityfeed'),
    url(r'^activityfeed', views.activityfeed, name='activityfeed'),

    url(r'^user_detail/(?P<user_id>\d+)$', views.user_detail, name='user_detail'),
    url(r'^user_detail/$', views.user_detail, name='user_detail_ajaxstub'),

    url(r'^change_password$', views.change_password, name='change_password'),
    url(r'^change_email$', views.change_email, name='change_email'),
    url(r'^reset_password$', views.reset_password, name='reset_password'),

    url(r'^user_ascents/(?P<user_id>\d+)$', views.user_ascents, name='user_ascents'),
    url(r'^upload_avatar$', views.upload_avatar, name='upload_avatar'),
    url(r'^delete_avatar$', views.delete_avatar, name='delete_avatar'),
    url(r'^register$', views.register, name='users.views.register'),
    url(r'^confirm/(?P<activation_key>.*)$', views.confirm, name='confirm'),
    url(r'^confirm_mail/(?P<activation_key>.*)$', views.confirm_email_change, name='confirm_email_change'),
    url(r'^login$',  LoginView.as_view(), name='django.contrib.auth.views.login'),
    url(r'^logout$', LogoutView.as_view(), name='django.contrib.auth.views.logout'),
    url(r'^route_histogram/(?P<user_id>\d+)$', views.user_route_histogram, name='user_route_histogram'),
    url(r'^test_confirmation$', views.test_confirmation, name='test_confirmation'),
    url(r'^test_message$', views.test_message, name='test_message'),
    url(r'^test_deletion$', views.test_deletion, name='test_deletion'),
    url(r'^test_success$', views.test_success, name='test_success'),

    url(r'^delete_user$', views.delete_user, name='delete_user'),

    url(r'^rest/revisions/(?P<user_id>\d+)$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/revisions$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/activities/(?P<user_id>\d+)$', classviews.RestUserActivities.as_view(), name='rest_user_activities'),
    url(r'^rest/ascents/(?P<user_id>\d+)$', classviews.RestUserAscents.as_view(), name='rest_user_ascents'),

    url(r'^rest/routework$', classviews.RouteWork.as_view(), name='rest_routework'),
    url(r'^rest/wallwork$', classviews.WallWork.as_view(), name='rest_wallwork'),
    url(r'^rest/tilerwork$', classviews.TilerWork.as_view(), name='rest_tilerwork'),
    url(r'^rest/panostitcherwork$', classviews.PanoStitcherWork.as_view(), name='rest_panostitcherwork'),

#    url(r'^rest/favroutes$', classviews.FavRoutes.as_view(), name='rest_favroutes'),
    url(r'^rest/favwalls$', classviews.FavWalls.as_view(), name='rest_favwalls'),

    url(r'^user_work/$', views.user_work, name='user_work'),
    url(r'^favourites/$', views.favourites, name='favourites'),
]

miroutes/templates/miroutes/route_timeline.html
{% load i18n %}
<ul id="route-timeline" class="timeline-itemlist">
</ul>
<button id='load-id' type='submit' data-page="1" onclick="loadTimeline();">{% trans "Show More" %}</button>
<script>
function format_date(date) {
    return date.toLocaleString();
}

function get_newsitem(data){
    return "<li>" +
        "<div class='timeline-item-date'>" + data.itemicon + " " + format_date(new Date(data.date)) + ":</div>" +
        "<div class='timeline-item'>" +
        "<div class='timeline-item-user'>" +
        "<a href='{%url 'users:user_detail_ajaxstub' %}" + data.user_id + "'>" + data.user_name + "</a>" +
        "<span class='timeline-item-what'> " + data.what + ":</span>" +
        "</div>" +
        "<img class='timeline-item-avatar' src='" + data.avatar + "' />" +
        "<div class='timeline-item-text'>" + data.text + "</div></div></li>";

}

function loadTimeline(){
    $.get(
        "{% url "miroutes:route_timeline_chunk" route_id=route.pk %}",
        {"page_num": $("#load-id").data('page')},
        function (data){
            var page = $("#load-id").data('page');
            if(data.length < 10)
                $("#load-id").hide();
            if(data.length == 0){
                if(page == 1)
                    $("#route-timeline").append("<li>{% trans "No events to show." %}</li>");
                return;
            }

            $.each(data, function (idx, item){
                if(typeof(item.comment) !== 'undefined'){
                    var comment_div = get_newsitem({
                        itemicon: '<i class="glyphicon glyphicon-comment timeline-item-icon"></i>',
                        date: item.comment.created,
                        user_id: item.comment.user_id,
                        user_name: item.comment.user_name,
                        what: "{% blocktrans with name=route.name %}commented on {{ name }}{% endblocktrans %}",
                        avatar: item.comment.avatar,
                        text: item.comment.comment
                    })
                    $("#route-timeline").append(comment_div);
                }else if(typeof(item.ascent) !== 'undefined'){
                    var ascent_div = get_newsitem({
                        itemicon: '<i class="glyphicon glyphicon-check timeline-item-icon"></i>',
                        date: item.ascent.date,
                        user_id: item.ascent.user_id,
                        user_name: item.ascent.user_name,
                        what: item.ascent.style + " {{ route.name }}",
                        avatar: item.ascent.avatar,
                        text: "{% trans "Rating" %}: " + item.ascent.rating
                    })
                    $("#route-timeline").append(ascent_div);
                }

            });
            $("#load-id").data('page', page + 1);
        });
    }
loadTimeline();
</script>

miroutes/templates/miroutes/tick_popup.html
{% extends request.is_ajax|yesno:"plain.html,base.html" %}
{% load i18n %}
{% if request.is_ajax is False %}
    {% block title %}
        cruxle.org - Tick {{ route.name }}
    {% endblock %}
    {% load static %}
{% endif %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4>
      <i class="glyphicon glyphicon-check"></i> {% blocktrans with name=route.name %}Tick {{ name }}{% endblocktrans %}
    </h4>
  </div>
  <div class="modal-body">
    <div class="form-errors"></div>
    <div id="ascent-form-container">
      {% crispy form %}
    </div>
    <div id="ascent-list-container">
      <h4 class="panel-title">
        <a href="#" onclick="$('#ascent-list').slideToggle();">
          <span class="glyphicon glyphicon-collapse-down"></span> {% trans "Other Ascents" %}
        </a>
      </h4>
      <br>
      <div id="ascent-list"></div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default btn-warning" data-dismiss="modal">{%trans "Cancel"%}</button>
    <button id="submit-button" class="submit-button btn btn-success">
      <i class="glyphicon glyphicon-check"></i> {% trans "Tick Route" %}
    </button>
  </div>

  <script>

    function displayAscentTable(){
        {% if request.user.is_anonymous %}
        $("#ascent-list-container").hide();
        {% else %}
        var url = '{% url "users:rest_user_ascents" user_id=request.user.pk %}';
        {% endif %}
        $.get({
            url: url,
            data: {
                route: {{ route.pk }}
            },
            success: function (response) {
                var table = $('<table/>').addClass('table table-hover table-responsive table-condensed table-striped');
                var body = $('<tbody/>');
                $.each(response, function(){
                    var id = this.id;
                    var date = new Date(this.date);
                    var note = '';
                    if(this.note) {
                        note = this.note.length > 20 ? this.note.substring(0, 20) + '...' : this.note;
                    }
                    // use this button to delete ascents but warn with popover
                    var $del = $('<a href="#" class="glyphicon glyphicon-trash">', {
                        'tabindex': '0',
                        'role': 'button',
                        'data-toggle': 'popover',
                        'data-placement': 'bottom',
                        'data-trigger': 'focus',
                      }).prop('title', '{% trans "Really?" %}')
                        .data('html', 'true')
                        .data('content', '<button class="btn btn-danger" onclick="delete_ascent(' + id + ');">{% trans "Do It!" %}</button>');
                   $del.popover();

                   var row = $('<tr>').attr('id', 'ascent' + this.id)
                        .append($('<td>').html(date.toLocaleDateString()))
                        .append($('<td>').html(note))
                        .append($('<td>').html(this.get_style_display))
                        .append($('<td>').html('<span class="ascent-rating"></span>'))
                        .append($('<td>')
                                .append($('<a href="#">')
                                        .on('click', function(){edit_ascent(id)})
                                        .append($('<span class="glyphicon glyphicon-pencil">'))))
                        .append($('<td>')
                                .append($del));

                    body.append(row);
                    rating(row.find("span.ascent-rating"), this.rating);

                });
                $('#ascent-list').empty().append(table.append(body));

                // manage display
                if(response.length > 0){
                    $("#ascent-list-container").show();

                    // only collapse if more than 3 entries
                    if(response.length > 3)
                        $("#ascent-list").slideUp();
                    else
                        $("#ascent-list").slideDown();
                }
                else
                    $("#ascent-list-container").hide();
            }
        });

    }

    function delete_ascent(ascentid){
        verboseJsonAjax({
            url: "{% url "miroutes:del_ascent" %}" + ascentid,
            success: function(){
                displayAscentTable();
            }
        });
    }

    function edit_ascent(ascentid){
        var submiturl = '{% url "miroutes:ascent_details" %}' + ascentid;
        $.get({
            url: submiturl,
            success: function (response) {
                $("#ascent-form-container").html(response);
                handle_ajax_form(submiturl);
            }
        });

    }

    function handle_ajax_form(submiturl) {
        /*
          Handle the click on submit and load a new form or close the
          parent modal if there is one (should have class .tick-modal).
         */

        var submit_button = $('.modal-footer #submit-button');

        submit_button.off().one('click', function (event) {
            event.preventDefault();

            var form = $("#ascent_form");
            var csrftoken = $.cookie('csrftoken');
            form.ajaxSubmit({
                url: submiturl,
                type: 'post',
                dataType: 'json',
                beforeSend: function (request) {
                    request.setRequestHeader("X-CSRFToken", csrftoken);
                },
                success: function (response) {
                    messageCallback(response);
                    response = JSON.parse(unescape(response));
                    if (response.success) {
                        // if we find a modal with class .tick-modal we close it
                        var modal = $(".tick-modal");
                        if(modal.length > 0)
                            modal.modal('hide');
                        else
                            displayAscentTable();
                    } else {
                        var messagediv = modal.find(".form-errors");
                        messagediv.html("Errors:<br><ul>");
                        $.each(response.data, function (field, value) {
                            messagediv.append("<li><b>" + field + "</b>: " + value + "</li>");
                        });
                        messagediv.append("</ul><br>");
                        handle_ajax_form(submiturl);
                    }
                }
            });
        });
    }

    $(document).ready(function () {
        handle_ajax_form("{% url "miroutes:add_ascent" route_id=route.pk %}");
        displayAscentTable();
    });
  </script>
{% endblock %}

miroutes/templates/miroutes/userpic_delete_confirmation.html
{% load i18n %}
<p>{% trans "Really delete this picture?" %}</p>
<button class='btn btn-danger' onclick='delete_pic({{ pic.pk }});'>{% trans "Do It!" %}</button>

miroutes/templates/miroutes/userpic_list.html
{% extends request.is_ajax|yesno:"base_ajax.html,base.html" %}
{% load thumbnail %}
{% load i18n %}

{% if request.is_ajax is False %}
{% block title %}
    {% if content == "personal" %}
    cruxle.org - {% trans "Userpics" %}
    {% else %}
    cruxle.org - {% trans "Info Material" %}
    {% endif %}
{% endblock %}
{% endif %}


{% block header %}
{% endblock %}

{% block content %}
<div class="userpic-panel">
    {% for userpic in pics %}
    <div class="row userpic-entry">
	<div class="col-xs-12 col-md-8 col-lg-6">
	    <a class='wall-thumb' href='{{ userpic.img.url }}'>
		<img src="{{ userpic.img|thumbnail_url:'materials_large' }}" class="img-responsive center-block">
	    </a>
	</div>
	<div class="col-xs-12 col-md-4 col-lg-6">
	    <div class="userpic-desc word-wrap-break-word">
		<h4>
		{{ userpic.description | safe | truncatewords_html:5 }}
		</h4>
	    </div>

	    <div class="userpic-details">
		{% trans "Posted by" %}
		<a href="{% url "users:user_detail" user_id=userpic.created_by.pk %}">
		    <!--img class="userpic-avatar" src="{{ userpic.created_by.userprofile.thumb_url }}"/-->
		    {{userpic.created_by.username}}
		</a>
		({{ userpic.created_at|date:"D d M Y" }})
		{% ifequal userpic.created_by request.user %}
		<a href="{% url "miroutes:userpic_edit" userpic_id=userpic.pk %}?next={{request.path}}">
		    <span class="glyphicon glyphicon-pencil"></span>
		</a>
		<a href="#"
		   tabindex="0" role="button"
		   data-toggle="popover"
		   data-trigger="focus"
		   data-placement="bottom"
		   data-title="{% trans "Confirm" %}"
		   data-html="true"
		   data-content="{% include "miroutes/userpic_delete_confirmation.html" with pic=userpic %}">
		    <span class="glyphicon glyphicon-trash"></span>
		</a>
		{% endifequal %}
		<div>
		  <small style="color: gray;">
		    {% trans "Linked to:" %}
		    {% for links in userpic.on_wall.all %}
		    <p><span class="mitopo-wall"></span> {{ links.name }}</p>
		    {% endfor %}
		    {% for links in userpic.on_route.all %}
		    <p><span class="mitopo-route"></span> {{ links.name }}</p>
		    {% endfor %}
		  </small>
		</div>

	    </div>

	    <br>

	    <div class="userpic-ext-url">
		{% if userpic.external_url %}
		<a href="{{userpic.external_url}}"
		   target="_blank">
		   <span class="glyphicon glyphicon-globe"></span> {% trans "External Source:" %} {{userpic.external_url|urlizetrunc:20}}
		</a>
		{% endif %}
	    </div>

	    {% if userpic.description|wordcount > 5 %}
	    <div class="userpic-desc">
		{{ userpic.description | safe }}
	    </div>
	    {% endif %}

	    <div class="userpic-comments">
		{% include 'micomments/show_comments.html' with thread_id=userpic.comment_thread chunk_size=5 %}
	    </div>

	</div> <!-- col description -->
    </div>

    <hr>

    {% empty %}
    <br>
    <div class="placholder-text">{% if content == "personal" %}{% trans "No Userpics available." %}{% else %}{% trans "No Info Material available." %}{% endif %}</div>
    {% endfor %}
    </div>
  <script>
    $(document).ready(function(){
	$('[data-toggle="popover"]').popover();
    });
  </script>

{% endblock %}