edit_spot/urls.py
from django.conf.urls import *
from rest_framework.routers import DefaultRouter

from edit_spot import views, classviews
from miroutes.model_choices import GRADE_CHOICES, AID_GRADE_CHOICES

from django.http import HttpResponse, JsonResponse
from rest_framework.routers import DefaultRouter

app_name = 'edit_spot'

do_nothing = lambda *args, **kwargs: HttpResponse()

route_geom_router = DefaultRouter()
route_geom_router.register(r'routegeometries', classviews.RouteGeometryViewSet, basename='routegeometry')

urlpatterns = [
url(r'^wall_img(?P<tiler_id>\d+)/edit$', views.edit_wall_img, name='edit_wall_img'),
url(r'^wall_img(?P<tiler_id>\d+)/revert(?P<version_id>\d+)$', views.revert_wall_img, name='revert_wall_img'),
url(r'^add_wall_img$', views.add_wall_img, name='add_wall_img'),
url(r'^add_wall_from_pano/(?P<pano_id>\d+)$', views.add_wall_from_pano, name='add_wall_from_pano'),

url(r'^wall_img(?P<tiler_id>\d+)/add_wall$', views.add_wall, name='add_wall'),
url(r'^wall(?P<wall_id>\d+)/routelist_chunk$', views.routelist_chunk, name='routelist_chunk'),

url(r'^edit_route/$', do_nothing, name='edit_route_noid'),
url(r'^edit_route/(?P<route_id>\d+)$', views.edit_route, name='edit_route'),
url(r'^deprecate_route/(?P<route_id>\d+)$', views.deprecate_route, name='deprecate_route'),
url(r'^deprecate_route/$', views.deprecate_route, name='deprecate_route'),
url(r'^route(?P<route_id>\d+)/add_material$', views.add_material, name='add_material'),
url(r'^route(?P<route_id>\d+)/link_materials$', views.link_materials, name='link_materials'),
url(r'^route(?P<route_id>\d+)/toggle_link_material/(?P<material_id>\d+)$', views.toggle_link_material, name='toggle_link_material'),
url(r'^route(?P<route_id>\d+)/toggle_link_material/$', do_nothing, name='toggle_link_material'),

url(r'^add_route$', views.add_route, name='add_route'),
url(r'^revert_route/route(?P<route_id>\d+)/version(?P<version_id>\d+)$', views.revert_route, name='revert_route'),
url(r'^revert_wall/wall(?P<wall_id>\d+)/version(?P<version_id>\d+)$', views.revert_wall, name='revert_wall'),

url(r'^wall(?P<wall_id>\d+)/edit_wall$', views.edit_wall, name='edit_wall'),
url(r'^wall(?P<wall_id>\d+)/del_wall$', views.del_wall, name='del_wall'),

url(r'^wallview(?P<wall_id>\d+)/link_routes$', views.link_routes, name='link_routes'),
url(r'^wallview(?P<wallview_id>\d+)/toggle_link_route/(?P<route_id>\d+)$', views.toggle_link_route, name='toggle_link_route'),
url(r'^wallview(?P<wallview_id>\d+)/toggle_link_route/$', do_nothing, name='toggle_link_route_noid'),
url(r'^wallview(?P<wallview_id>\d+)/store_geojson$', views.store_geojson, name='store_geojson'),
url(r'^wallview(?P<wallview_id>\d+)/edit_gym_route$', views.edit_gym_route, name='edit_gym_route'),
url(r'^wallview(?P<wallview_id>\d+)/edit_gym_route(?P<route_id>\d+)$', views.edit_gym_route, name='edit_gym_route'),
url(r'^changeset/(?P<wallview1_id>\d+)/(?P<wallview2_id>\d+)$', views.wallview_changeset, name='wallview_changeset'),

url(r'^wall(?P<wall_id>\d+)/link_materials$', views.link_materials, name='link_materials'),
url(r'^wall(?P<wall_id>\d+)/toggle_link_material/(?P<material_id>\d+)$', views.toggle_link_material, name='toggle_link_material'),
url(r'^wall(?P<wall_id>\d+)/toggle_link_material/$', do_nothing, name='toggle_link_material'),
url(r'^wall(?P<wall_id>\d+)/add_material$', views.add_material, name='add_material'),

url(r'^wall(?P<wall_id>\d+)/draw_routes$', views.draw_routes, name='draw_routes'),
url(r'^wall(?P<wall_id>\d+)/publish_wall$', views.publish_wall, name='publish_wall'),
url(r'^wall(?P<wall_id>\d+)/reset_dev_wall$', views.reset_dev_wall, name='reset_dev_wall'),

url(r'^wall(?P<wall_id>\d+)/decorate_wall$', views.decorate_wall, name='decorate_wall'),
url(r'^wall(?P<wall_id>\d+)/finish_wall_edit$', views.finish_wall_edit, name='finish_wall_edit'),
url(r'^wall(?P<wall_id>\d+)/delete$', views.delete_wall, name='delete_wall'),

url(r'^wall_img(?P<tiler_id>\d+)/rotate_right$', views.rotate_wall_img_right, name='rotate_img_right'),
url(r'^wall_img(?P<tiler_id>\d+)/rotate_left$', views.rotate_wall_img_left, name='rotate_img_left'),

url(r'^routegeometry(?P<geom_id>\d+)/delete$', views.del_geom, name='del_geom'),
url(r'^rest/tiler/(?P<pk>[0-9]+)/$', classviews.TilerDetail.as_view(), name='get_tiler'),

url(r'^grades_table$', lambda *args, **kwargs:JsonResponse(GRADE_CHOICES, safe=False), name='grades_table'),
url(r'^aid_grades_table$', lambda *args, **kwargs:JsonResponse(AID_GRADE_CHOICES, safe=False), name='aid_grades_table')
]

urlpatterns += route_geom_router.urls

mitopo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import *
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from rest_framework_swagger.views import get_swagger_view

from mitopo.views import schema_view, greeter_index

app_name = 'mitopo'

urlpatterns = [
    path(r'robots.txt', TemplateView.as_view(template_name='mitopo/robots.txt', content_type='text/plain')),
    path(r'admin/', admin.site.urls),
    path("soc/", include("social_django.urls", namespace="social")),
    path(r'i18n/', include('django.conf.urls.i18n')),
    path(r'micomments/', include('micomments.urls')),
    path(r'upload/', include('django_file_form.urls')),
    url(r'apidoc/', schema_view)
]

urlpatterns += i18n_patterns(
    path('', greeter_index, name='greeter_index'),
    path('miroutes/', include('miroutes.urls')),
    path('edit_spot/', include('edit_spot.urls')),
    path('generic_markers/', include('generic_markers.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('stitcher/', include('stitcher.urls')),
    path('micontactform/', include('micontactform.urls')),
    path('miexport/', include('miexport.urls')),
    path('postbox/', include('postbox.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

)

# if in debug mode, redirect static requests to media_ROOT
from django.conf import settings
from  django.views import static

if settings.DEBUG == True:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }), ]

stitcher/urls.py
from django.conf.urls import *

from stitcher import views, classviews

app_name = 'stitcher'

urlpatterns = [
    url(r'^add_pano$', views.add_pano, name='add_pano'),
    url(r'^pano(?P<pano_id>\d+)/view$', views.view_pano, name='view_pano'),
    url(r'^pano(?P<pano_id>\d+)/run_pano_stitcher$', views.run_pano_stitcher, name='run_pano_stitcher'),

    url(r'^pano(?P<pk>[0-9]+)/get_pano$', classviews.PanoDetail.as_view(), name='get_pano'),
    url(r'^processing_request', views.processing_request_page, name='processing_request_page'),
]

users/urls.py
from django.conf.urls import *
from django.contrib.auth.views import LoginView, LogoutView

from users import views
from users import classviews

from django.http import HttpResponse
do_nothing = lambda *args, **kwargs: HttpResponse()

app_name='users'

urlpatterns = [
    url(r'^profile', views.profile, name='profile'),
    url(r'^activityfeed/(?P<user_id>\d+)', views.activityfeed, name='activityfeed'),
    url(r'^activityfeed', views.activityfeed, name='activityfeed'),

    url(r'^user_detail/(?P<user_id>\d+)$', views.user_detail, name='user_detail'),
    url(r'^user_detail/$', views.user_detail, name='user_detail_ajaxstub'),

    url(r'^change_password$', views.change_password, name='change_password'),
    url(r'^change_email$', views.change_email, name='change_email'),
    url(r'^reset_password$', views.reset_password, name='reset_password'),

    url(r'^user_ascents/(?P<user_id>\d+)$', views.user_ascents, name='user_ascents'),
    url(r'^upload_avatar$', views.upload_avatar, name='upload_avatar'),
    url(r'^delete_avatar$', views.delete_avatar, name='delete_avatar'),
    url(r'^register$', views.register, name='users.views.register'),
    url(r'^confirm/(?P<activation_key>.*)$', views.confirm, name='confirm'),
    url(r'^confirm_mail/(?P<activation_key>.*)$', views.confirm_email_change, name='confirm_email_change'),
    url(r'^login$',  LoginView.as_view(), name='django.contrib.auth.views.login'),
    url(r'^logout$', LogoutView.as_view(), name='django.contrib.auth.views.logout'),
    url(r'^route_histogram/(?P<user_id>\d+)$', views.user_route_histogram, name='user_route_histogram'),
    url(r'^test_confirmation$', views.test_confirmation, name='test_confirmation'),
    url(r'^test_message$', views.test_message, name='test_message'),
    url(r'^test_deletion$', views.test_deletion, name='test_deletion'),
    url(r'^test_success$', views.test_success, name='test_success'),

    url(r'^delete_user$', views.delete_user, name='delete_user'),

    url(r'^rest/revisions/(?P<user_id>\d+)$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/revisions$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/activities/(?P<user_id>\d+)$', classviews.RestUserActivities.as_view(), name='rest_user_activities'),
    url(r'^rest/ascents/(?P<user_id>\d+)$', classviews.RestUserAscents.as_view(), name='rest_user_ascents'),

    url(r'^rest/routework$', classviews.RouteWork.as_view(), name='rest_routework'),
    url(r'^rest/wallwork$', classviews.WallWork.as_view(), name='rest_wallwork'),
    url(r'^rest/tilerwork$', classviews.TilerWork.as_view(), name='rest_tilerwork'),
    url(r'^rest/panostitcherwork$', classviews.PanoStitcherWork.as_view(), name='rest_panostitcherwork'),

#    url(r'^rest/favroutes$', classviews.FavRoutes.as_view(), name='rest_favroutes'),
    url(r'^rest/favwalls$', classviews.FavWalls.as_view(), name='rest_favwalls'),

    url(r'^user_work/$', views.user_work, name='user_work'),
    url(r'^favourites/$', views.favourites, name='favourites'),
]

stitcher/forms.py
"""Stitcher Forms"""
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML
from django import forms
from django.forms import MultipleChoiceField, ModelMultipleChoiceField
from django.utils.translation import ugettext_lazy as _
from django_file_form.forms import FileFormMixin, MultipleUploadedFileField

from miroutes.models import License
from miroutes.widgets import LicenseChooser


def get_licenses():
    return list(License.objects.all().order_by("-required", "short_name"))

class PanoForm(FileFormMixin, forms.Form):
    img = MultipleUploadedFileField(label=_('Panorama Parts'))
    licenses = ModelMultipleChoiceField(queryset=License.objects.all(), widget = LicenseChooser(licenses_callback=get_licenses))

    def __init__(self, *args, **kwargs):
        super(PanoForm, self).__init__(*args, **kwargs)

        # Use crispy-forms to generate the code
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-1 col-md-2 col-xs-12'
        self.helper.field_class = 'col-lg-7 col-md-8 col-xs-12'
        self.helper.layout = Layout(*list(self.fields.keys()))  # use all fields

        self.helper.form_id = 'pano-form'
        self.helper.form_method = 'post'
        self.helper.layout.append(HTML("""
        {% load i18n %}
        <a type="button" href="{{ next_page }}" class="btn btn-info">
        <i class="glyphicon glyphicon-arrow-left" aria-hidden="true"></i>
        {% trans "Back" %}
        </a>
        <button id="submit-button" type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-cog"></span> {% trans "Try it!" %}</button>
        """))

stitcher/views.py
# -*- coding: utf-8 -*-


from django.utils.translation import ugettext_lazy as _

from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from django.contrib.auth.decorators import permission_required

from stitcher.models import PanoPart, Pano
from stitcher.forms import PanoForm
# Create your views here.

@permission_required('miroutes.add_wall')
def add_pano(request):
    """Add additional material."""
    next_page = request.GET.get('next', reverse('edit_spot:add_wall_img'))

    class ImageUploadError(Exception):
        pass

    if request.POST:
        form = PanoForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                images = form.cleaned_data['img']

                if images is None:
                    messages.add_message(request, messages.ERROR, _('The Images could not be sent to the server, please ask us whats going on'))
                    raise ImageUploadError('Images is None')

                if len(images) < 2:
                   messages.add_message(request, messages.ERROR, _('Need at least 2 images to stitch a panorama'))
                   raise ImageUploadError('Less than 2 Images provided')

                pano = Pano()
                pano.created_by = request.user
                pano.save()

                pano.licenses.set(form.cleaned_data['licenses'])
                pano.save()

                for image in images:
                    part = PanoPart(img=image, pano=pano)
                    part.save()
                form.delete_temporary_files()
                messages.add_message(request, messages.SUCCESS,
                                     _('Saved Pano Parts!'))

                view_pano_url = reverse('stitcher:run_pano_stitcher', kwargs={'pano_id': pano.id})
                processing_url = '{}/?next={}'.format(reverse('stitcher:processing_request_page'), view_pano_url)
                return redirect(processing_url)

            except ImageUploadError:
                pass # go back to original page and show form errors

        else:
            messages.add_message(request, messages.ERROR,
                                 _('Failed to save Pano Parts!'))

    else:
        form = PanoForm()

    context = {
        'form': form,
        'next_page': next_page
    }
    return render(request, 'stitcher/add_pano.html', context)

@permission_required('miroutes.add_wall')
def view_pano(request, pano_id):
    pano = get_object_or_404(Pano, pk=pano_id)

    context = {
        'pano': pano,
    }

    return render(request, 'stitcher/view_pano.html', context)

@permission_required('miroutes.add_wall')
def run_pano_stitcher(request, pano_id):
    pano = get_object_or_404(Pano, pk=pano_id)

    pano.run_stitching()

    return redirect(reverse('stitcher:view_pano', kwargs={'pano_id': pano.id}))

def processing_request_page(request):
    """ This just displays a spinner and forwards to another page, which is given with ?next as url argument"""
    next_page = request.GET.get('next', reverse('miroutes:index'))
    return render(request, 'stitcher/processing_request_page.html', {'next_page': next_page})

stitcher/templates/stitcher/add_pano.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% load thumbnail %}

{% load i18n %}

{% block title %}
    cruxle.org - {% trans "Stitch Panoramas" %}
{% endblock %}

{% block extra_assets %}
    <link rel="stylesheet" href="{% static "edit_spot/css/main.css" %}"/>
    {% include 'includes/upload_template.html' %}
{% endblock %}

{% block content %}
  <script type="text/javascript">
    $(document).ready(function () {
        $("#pano-form").on('submit', function (evt) {
            evt.preventDefault();
            // Check if one file is selected
            var numfiles = $(".file-uploader-container").fineUploader('getUploads', {status: qq.status.UPLOAD_SUCCESSFUL}).length;
            if (numfiles < 1) {
                append_message("{% trans "Select and upload panorama images." %}", "danger");
                return none;
            }
            $("#pano-form")[0].submit();
        });

        initUploadFields($('#pano-form'));
        $(".qq-upload-button div").html("<div>{% trans "Upload Multiple Pictures!" %}</div>");
    });
  </script>
  <div class="col-xs-12 col-md-8 col-md-push-2 col-lg-push-1">
    <h4>
      {% trans "Add Panorama Image" %}
    </h4>
    <p><span class='glyphicon glyphicon-info-sign'></span>
      {% trans "Upload up to 20 images to form a panoramic picture." %}</p>
    <p><span class='glyphicon glyphicon-info-sign'></span>
      {% blocktrans with path=request.path %}
        The open-source tool <a href="http://hugin.sourceforge.net/">Hugin</a>
      is used to stitch the images. Better results may be achieved by downloading Hugin and using the tool locally.
    {% endblocktrans %}
    </p>
      {% crispy form %}
  </div>

{% endblock %}

stitcher/templates/stitcher/processing_request_page.html
{% extends "base.html" %}
{% load static %}

{% load i18n %}

{% block title %}
    cruxle.org - {% trans "Processing..." %}
{% endblock %}

{% block content %}
<div class="col-xs-12 col-md-10 col-lg-8 col-sm-push-1 text-center top-buffer-margin">

<h4>{% trans "We are working on it, just a sec..." %} </h4>
<div id='processing_spinner' class='top-buffer-margin text-center'>
    <i class="fa fa-spinner fa-spin fa-4x"></i>
</div>
<small>
{% trans "You will be forwarded shortly..." %}
<p>
<a href="{{next_page}}">{{next_page}}</a>
</p>
</small>
</div>

<script>
$(document).ready(function () {
    window.location.href = '{{next_page}}';
});
</script>

{% endblock %}

stitcher/templates/stitcher/view_pano.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% load thumbnail %}

{% load i18n %}

{% block title %}
    cruxle.org - {% trans "Stitch Panoramas" %}
{% endblock %}

{% block extra_assets %}
    <link rel="stylesheet" href="{% static "edit_spot/css/main.css" %}"/>
    {% include 'includes/upload_template.html' %}
{% endblock %}

{% block content %}

  <div class="col-xs-12">
    <h4>
      <a href="{% url "stitcher:add_pano" %}"><span class="glyphicon glyphicon-chevron-left"></span></a> {% trans "View Panorama Image Stitcher" %}
    </h4>
    <p><span class='glyphicon glyphicon-info-sign'></span> {% trans "Please wait... we will try our best to stitch your panorama. This may take a while..." %}</p>
    <p><span class='glyphicon glyphicon-info-sign'></span> {% trans "You can watch the progress or come back later. We will send you an email when the stitching is finished." %}</p>
    <p><span class='glyphicon glyphicon-info-sign'></span> {% trans "For best results, we recommend you use pictures which have at least 10-20% overlap and posses correct EXIF Tags about the Field of View and camera-optics settings." %}</p>
    {% if pano.img %}
    <div id="pano_view" class="top-buffer-margin wide_popover_container">
    <a href="#"
       data-toggle='popover'
       tabindex="0"
       role="button"
       title='{%trans "Additional Info and Exif-Data" %}'
       data-trigger='focus'
       data-placement='bottom'
       data-content="
       <a href='{{pano.img.url}}'>{% trans 'Link to Original File' %} : {{pano.img.name}}</a>
       <ul class='' title='Exif Tags'>
         {% for key, value in pano.get_exif.items|dictsort:"0.lower" %}
           <li class=''> <span class='label label-default'>{{key}}</span> {{value}} </li>
         {% endfor %}
       </ul>">
       <img src="{{pano.img|thumbnail_url:'pano'}}"
            alt="Panorama image: {{pano.img.url}}"
            class="img-fluid">
    </a>
    <br>
    <br>
    <a href="{% url "edit_spot:add_wall_from_pano" pano_id=pano.id %}"
       class="btn btn-success">
      <span class="glyphicon glyphicon-ok"></span> {% trans "Create a wall from this Image" %}
    </a>
    </div>
    {% endif %}


    <div id="pano_detail" class="top-buffer-margin wide_popover_container">
      {% for part in pano.panopart_set.all %}
        <a href="#"
           data-toggle='popover'
           tabindex="0"
           role="button"
           title='{%trans "Additional Info and Exif-Data" %}'
           data-trigger='focus'
           data-placement='bottom'
           data-content="<a href='{{part.img.url}}'>{% trans 'Link to Original File' %} : {{part.img.name}}</a>
           <ul class='' title='Exif Tags'>
           {% for key, value in part.get_exif.items|dictsort:"0.lower" %}
           <li class=''> <span class='label label-default'>{{key}}</span> {{value}} </li>
           {% endfor %}
           </ul>">
          <img src="{{part.img|thumbnail_url:'pano_parts'}}"
               alt="{{part.img|thumbnail_url:'materials'}}"
               class="img-thumbnail">
        </a>
      {% endfor %}
    </div>
    <br>
    <br>
    <br>

    <div id='panostitcher-status-div' class="top-buffer-margin"></div>
    <br>
    <br>
    {% include "includes/report_content_element.html" %}
    <br>
    <br>
  </div>

  <script type="text/javascript">
    function updateStatus(){
        var url = '{% url "stitcher:get_pano" pk=pano.id %}';
        $.getJSON(url, function(data) {
            out = data;
            var $statusdiv = $('#panostitcher-status-div');
            var title_strings = {
                'output_creating': 'Creating Panorama Project',
                'output_cpfind': 'Searching overlapping points',
                'output_cpclean': 'Removing weird controls points',
                'output_linefind': 'Searching for a horizon',
                'output_optimising': 'Optimising control points',
                'output_cropping': 'Determine Panorama Image size',
                'output_stitching': 'Stitching Panorama',
                'output_blending': 'Blending Panorama',
                'output_convert_2_png': 'Creating PNG Image',
                'output_enhancing': 'Applying Generic Image Filters',
            };

            if($('#'+'stitching_in_progress_spinner').length === 0) {
                var progress_spinner = $('<span>', {id: 'stitching_in_progress_spinner', text: gettext("Stitching in progress...")}).append($('<i>',{class: "fa fa-spinner fa-spin"}));
                progress_spinner.appendTo($statusdiv);
            }

            for(key in data) {
                    if(!(key in title_strings)) { continue; }
                    if(!data[key]) {
                        text=null;
                    }else{
                        text = data[key].slice(2, data[key].length -1); // remove the b' at the beginning of the strings
                        // replace some special vars
                        text = text.replace(/\\n/g, '\n');
                        text = text.replace(/\\t/g, '\t');
                    }

                    if($statusdiv.find('#'+key+'body').length == 0) {
                        var $panel = $('<div>', {
                            id: key,
                            class: 'panel panel-default',
                        });
                        var $panelheading = $('<div>', {
                            id: key+'heading',
                            class: 'panel-heading',
                            text: gettext(title_strings[key]),
                        });
                        var $panelbody = $('<div>', {
                            id: key+'body',
                            class: 'panel-body',
                            style: 'display:none; white-space:pre-line;',
                            text: gettext(text),
                        });
                        $panelheading.appendTo($panel);
                        $panelbody.appendTo($panel);

                        $panel.appendTo($statusdiv);

                        $panel.on('click', function(e){
                            var panel = $(this);
                            var panelbody = panel.find('.panel-body');
                            console.log('panelbody',panelbody.text);
                            if(panelbody.text().length !== 0) {
                                panelbody.toggle();
                            }
                        });

                    } else {
                        var $panel = $statusdiv.find('#'+key);
                        var $panelheading = $panel.find('#'+key+'heading');
                        var $panelbody = $panel.find('#'+key+'body');
                        $panelbody.text(gettext(text));
                    }

                    if (text) {
                        $panel.addClass('panel-success');
                        if($panelheading.find('.check_broebbler').length===0){
                            var check_broebbler = $('<span>', {
                                class: 'check_broebbler glyphicon glyphicon-ok text-success',
                            });
                            $panelheading.append(check_broebbler);
                        }
                        if($panelheading.find('.info_broebbler').length===0){
                            var info_broebbler = $('<span>', {
                                class: 'info_broebbler glyphicon glyphicon-info-sign text-info pull-right',
                            });
                            $panelheading.append(info_broebbler);
                        }
                        $panel.css('cursor', 'pointer');
                    }

                    if(data.output_error) {
                        if (data.output_error.toLowerCase().indexOf(key) >= 0) { // this key here is mentioned in error msg...
                            $panel.addClass('panel-danger');
                            $panelheading.find('.check_broebbler').remove();
                            if($panelheading.find('.alert_broebbler').length===0){
                                var alert_broebbler = $('<span>', {
                                    class: 'alert_broebbler glyphicon glyphicon-alert text-danger',
                                });
                                $panelheading.append(alert_broebbler);
                            }
                            var $error = $('<div>', {
                                id: key+'error',
                                class: 'panel-body-error',
                                style: 'white-space:pre-line;',
                                text: 'ERROR in ' + gettext(data.output_error),
                            });
                            $error.appendTo($panelbody);
                        }
                        $('#stitching_in_progress_spinner').empty();
                    }
            };

            if(data.status == 100){
                location.reload();
            }

            if(data.output_error) {
                if($statusdiv.find('#try_again_button').length === 0) {
                    //$statusdiv.append($('<a>', {
                    //    id: 'try_again_button',
                    //    href: "{% url "stitcher:run_pano_stitcher" pano_id=pano.pk %}",
                    //    class: "btn btn-default",
                    //}).append($('<span>', {
                    //    class: "glyphicon glyphicon-repeat",
                    //    text: gettext("Try again!"),
                    //})));
                }
            }
        });

    }

    $(document).ready(function () {
        {% if not pano.img %}
        updateStatus();
        setInterval(function () {
            updateStatus();
        }, 3000);
        {% endif %}
    });
  </script>
{% endblock %}