miroutes/urls.py
from django.conf.urls import *
from rest_framework.routers import DefaultRouter

from miroutes import views
from miroutes import classviews
from django.http import HttpResponse
do_nothing = lambda *args, **kwargs: HttpResponse()

app_name = 'miroutes'

route_router = DefaultRouter()
route_router.register(r'rest/routes', classviews.RouteViewSet, basename='rest-route')

urlpatterns = [ url(r'^$', views.index, name='index'),
url(r'^search/', views.search, name='search'),
url(r'^about/', views.about, name='about'),
url(r'^imprint/', views.imprint, name='imprint'),
url(r'^license/(?P<license_key>[0-9a-z-]+)$', views.license, name='license'),
url(r'^privacy/', views.privacy, name='privacy'),
url(r'^news/', views.news, name='news'),
url(r'^help/', views.help, name='help'),
url(r'^wall_selection/', views.wall_selection, name='wall_selection'),
url(r'^check_wallview_updates/(?P<since>\d+)$', views.check_wallview_updates, name='check_wallview_updates'),

url(r'^pic(?P<userpic_id>\d+)/$', views.userpic, name='userpic'),
url(r'^pic(?P<userpic_id>\d+)/edit$', views.userpic_edit, name='userpic_edit'),
url(r'^pic$', do_nothing, name='userpic_stub'),
url(r'^picdel(?P<userpic_id>\d+)$', views.del_userpic, name='del_userpic'),
url(r'^picdel$', do_nothing, name='del_userpic_noid'),

url(r'^wall(?P<wall_id>\d+)/add_userpic', views.add_userpic, name='add_userpic'),
url(r'^route(?P<route_id>\d+)/add_userpic', views.add_userpic, name='add_userpic'),
url(r'^wall(?P<wall_id>\d+)/userpic_display$', views.userpic_display, name='userpic_display'),
url(r'^route(?P<route_id>\d+)/userpic_display$', views.userpic_display, name='userpic_display'),
url(r'^wall(?P<wall_id>\d+)/userpics', views.show_userpics, name='show_userpics'),
url(r'^route(?P<route_id>\d+)/userpics', views.show_userpics, name='show_userpics'),

url(r'^wall(?P<wall_id>\d+)/show_on_map', views.wall_on_map, name='wall_on_map'),
url(r'^wall(?P<wall_id>\d+)/dev$', views.wall_detail_dev, name='wall_detail_dev'),
url(r'^wall(?P<wall_id>\d+)/$', views.wall_detail, name='wall_detail'),
url(r'^wall(?P<wall_id>\d+)/just-published$', lambda *args, **kwargs:views.wall_detail(*args, **kwargs, just_published=True), name='wall_detail_published'),
url(r'^wall$', do_nothing, name='wall_detail_stub'),
url(r'^wall(?P<wall_id>\d+)/route_histogram$', views.wall_route_histogram, name='wall_route_histogram'),
url(r'^wall(?P<wall_id>\d+)/popup$', views.wall_popup, name='wall_popup'),
url(r'^wall(?P<wall_id>\d+)/routes$', views.wall_routelist, name='wall_routelist'),
url(r'^wall(?P<wall_id>\d+)/viewed$', views.wall_viewed, name='wall_viewed'),
url(r'^wall(?P<wall_id>\d+)/addfav$', views.wall_toggle_favourite, name='wall_toggle_favourite'),
url(r'^rest/wall/(?P<pk>\d+)$', classviews.RestWall.as_view(), name='rest_wall'),
url(r'^rest/news$', classviews.NewsViewSet.as_view(), name='rest_news'),
url(r'^rest/wall_activity/(?P<wall_id>\d+)$', classviews.RestWallActivity.as_view(), name='rest_wall_activity'),

url(r'^route(?P<route_id>\d+)$', views.route_detail, name='route_detail'),
url(r'^route$', do_nothing, name='route_detail_stub'),
url(r'^rest/route_activity/(?P<route_id>\d+)$', classviews.RestRouteActivity.as_view(), name='rest_route_activity'),
url(r'^route/short_info(?P<route_id>\d+)$', views.route_short_info, name='route_short_info'),
url(r'^route/short_info$', views.route_short_info, name='route_short_info'),
url(r'^route(?P<route_id>\d+)/timeline_chunk$', views.route_timeline_chunk, name='route_timeline_chunk'),
url(r'^route(?P<route_id>\d+)/qrcode$', views.route_qrcode, name='route_qrcode'),
url(r'^tick_route/(?P<route_id>\d+)$', views.tick_route, name='tick_route'),
url(r'^tick_route/$', views.tick_route, name='tick_route'),

url(r'^ticked/(?P<route_id>\d+)$', views.add_ascent, name='add_ascent'),
url(r'^ticked/$', views.add_ascent, name='add_ascent'),
url(r'^save_mapview$', views.save_mapview, name='save_mapview'),
url(r'^save_baselayer$', views.save_baselayer, name='save_baselayer'),
url(r'^ascent/details(?P<ascent_id>\d+)$', views.ascent_details, name='ascent_details'),
url(r'^ascent/details$', views.ascent_details, name='ascent_details'),
url(r'^ascent/delete(?P<ascent_id>\d+)$', views.del_ascent, name='del_ascent'),
url(r'^ascent/delete$', views.del_ascent, name='del_ascent'),

url(r'toggle_show_inactive', views.toggle_show_inactive, name='toggle_show_inactive'),
url(r'^filter_labels/$', do_nothing, name='filter_labels_ng'),
url(r'^filter_labels/(?P<grade_system>\d)$', views.get_filter_labels, name='filter_labels'),
]

urlpatterns += route_router.urls


from django.contrib.sitemaps.views import sitemap
from miroutes.sitemaps import sitemaps
from django.urls import path
from django.views.decorators.cache import cache_page

urlpatterns += [path('sitemap.xml', cache_page(60 * 60 * 24)(sitemap), {
    'sitemaps': sitemaps,
    'template_name': 'sitemap/MiroutesSitemap.html',},
    name='sitemap'), ]

mitopo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import *
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from rest_framework_swagger.views import get_swagger_view

from mitopo.views import schema_view, greeter_index

app_name = 'mitopo'

urlpatterns = [
    path(r'robots.txt', TemplateView.as_view(template_name='mitopo/robots.txt', content_type='text/plain')),
    path(r'admin/', admin.site.urls),
    path("soc/", include("social_django.urls", namespace="social")),
    path(r'i18n/', include('django.conf.urls.i18n')),
    path(r'micomments/', include('micomments.urls')),
    path(r'upload/', include('django_file_form.urls')),
    url(r'apidoc/', schema_view)
]

urlpatterns += i18n_patterns(
    path('', greeter_index, name='greeter_index'),
    path('miroutes/', include('miroutes.urls')),
    path('edit_spot/', include('edit_spot.urls')),
    path('generic_markers/', include('generic_markers.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('stitcher/', include('stitcher.urls')),
    path('micontactform/', include('micontactform.urls')),
    path('miexport/', include('miexport.urls')),
    path('postbox/', include('postbox.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

)

# if in debug mode, redirect static requests to media_ROOT
from django.conf import settings
from  django.views import static

if settings.DEBUG == True:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }), ]

postbox/urls.py
from django.conf.urls import *

from postbox import views
from postbox import classviews

app_name = 'postbox'

urlpatterns = [
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^send(?P<user_id>\d+)/$', views.send_message, name='send_message'),
    url(r'^replyTo(?P<thread_id>\d+)/$', views.reply, name='reply'),
    url(r'^toggle(?P<thread_id>\d+)/$', views.thread_read, name='toggle_read'),
    url(r'^rest/threads$', classviews.ThreadList.as_view(), name='rest_threads'),
]

users/urls.py
from django.conf.urls import *
from django.contrib.auth.views import LoginView, LogoutView

from users import views
from users import classviews

from django.http import HttpResponse
do_nothing = lambda *args, **kwargs: HttpResponse()

app_name='users'

urlpatterns = [
    url(r'^profile', views.profile, name='profile'),
    url(r'^activityfeed/(?P<user_id>\d+)', views.activityfeed, name='activityfeed'),
    url(r'^activityfeed', views.activityfeed, name='activityfeed'),

    url(r'^user_detail/(?P<user_id>\d+)$', views.user_detail, name='user_detail'),
    url(r'^user_detail/$', views.user_detail, name='user_detail_ajaxstub'),

    url(r'^change_password$', views.change_password, name='change_password'),
    url(r'^change_email$', views.change_email, name='change_email'),
    url(r'^reset_password$', views.reset_password, name='reset_password'),

    url(r'^user_ascents/(?P<user_id>\d+)$', views.user_ascents, name='user_ascents'),
    url(r'^upload_avatar$', views.upload_avatar, name='upload_avatar'),
    url(r'^delete_avatar$', views.delete_avatar, name='delete_avatar'),
    url(r'^register$', views.register, name='users.views.register'),
    url(r'^confirm/(?P<activation_key>.*)$', views.confirm, name='confirm'),
    url(r'^confirm_mail/(?P<activation_key>.*)$', views.confirm_email_change, name='confirm_email_change'),
    url(r'^login$',  LoginView.as_view(), name='django.contrib.auth.views.login'),
    url(r'^logout$', LogoutView.as_view(), name='django.contrib.auth.views.logout'),
    url(r'^route_histogram/(?P<user_id>\d+)$', views.user_route_histogram, name='user_route_histogram'),
    url(r'^test_confirmation$', views.test_confirmation, name='test_confirmation'),
    url(r'^test_message$', views.test_message, name='test_message'),
    url(r'^test_deletion$', views.test_deletion, name='test_deletion'),
    url(r'^test_success$', views.test_success, name='test_success'),

    url(r'^delete_user$', views.delete_user, name='delete_user'),

    url(r'^rest/revisions/(?P<user_id>\d+)$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/revisions$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/activities/(?P<user_id>\d+)$', classviews.RestUserActivities.as_view(), name='rest_user_activities'),
    url(r'^rest/ascents/(?P<user_id>\d+)$', classviews.RestUserAscents.as_view(), name='rest_user_ascents'),

    url(r'^rest/routework$', classviews.RouteWork.as_view(), name='rest_routework'),
    url(r'^rest/wallwork$', classviews.WallWork.as_view(), name='rest_wallwork'),
    url(r'^rest/tilerwork$', classviews.TilerWork.as_view(), name='rest_tilerwork'),
    url(r'^rest/panostitcherwork$', classviews.PanoStitcherWork.as_view(), name='rest_panostitcherwork'),

#    url(r'^rest/favroutes$', classviews.FavRoutes.as_view(), name='rest_favroutes'),
    url(r'^rest/favwalls$', classviews.FavWalls.as_view(), name='rest_favwalls'),

    url(r'^user_work/$', views.user_work, name='user_work'),
    url(r'^favourites/$', views.favourites, name='favourites'),
]

users/models.py
import os

import time
from PIL import Image
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import JSONField
from django.templatetags.static import static
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from reversion.models import Version, Revision
from django.utils.translation import ugettext_lazy as _

from mitopo.storage import OverwriteStorage
from mitopo.util import md5sum_file

USERS_BASE_FOLDER = "users"
AVATAR_FOLDER = "avatar"
AVATAR_FULL = "fullsize"
AVATAR_MEDIUM = "medium"
AVATAR_THUMB = "thumb"
AVATAR_FILE_ENDING = ".png"
THUMB_SIZE = 64
MEDIUM_SIZE = 300


def get_avatar_upload_path(userprofile, fname):

    # This could be covered by python 3 type hints, if the UserProfile class would be defined before this
    # function, but the UserProfile has a dependency to this function so we can't declare
    # it before the function. The workaround is to check at runtime.
    if type(userprofile) is not UserProfile:
        raise Exception("ERROR: get_avatar_upload_path was called with wrong argument. UserProfile expected as first argument")

    path = os.path.join(USERS_BASE_FOLDER, str(userprofile.pk), AVATAR_FOLDER, AVATAR_FULL + os.path.splitext(fname)[1])
    return path


def ensure_dir(f):
    d = os.path.dirname(f)
    if not os.path.exists(d):
        os.makedirs(d)


puzzle_map = {
    'add_route': 5,
    'edit_route': 3,
    'revert_route': 0,
    'add_wall': 30,
    'add_wall_img': 50,
    'edit_wall': 5,
    'revert_wall': 0,
    'revert_wall_img': 0,
    'link_route': 2,
    'unlink_route': 0,
    'edit_routegeometry': 3,
    'add_marker': 3,
    'move_marker': 2,
    'delete_marker': 0,
    'publish_wallview': 5,
    'revert_wallview': 0,
    'add_material': 10,
    'add_userpic': 5
}


def get_puzzles(key):
    """Obtain puzzle amount for a given key and 0 if none is defined."""
    return puzzle_map.get(key, 0)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    activation_key = models.CharField(max_length=40, blank=True, null=True)
    key_expires = models.DateTimeField(blank=True, null=True)
    avatar = models.ImageField(blank=True, upload_to=get_avatar_upload_path, storage=OverwriteStorage())
    puzzle_pieces = models.BigIntegerField(default=0)

    last_map_view = JSONField(blank=True, null=True)
    baselayer = models.CharField(max_length=30, blank=True, null=True)
    favourite_walls = models.ManyToManyField('miroutes.Wall', blank=True)

    # new adress if changed
    new_mail = models.EmailField(blank=True, null=True)

    # mail options
    message_mail = models.BooleanField(
        default=True,
        verbose_name=_("Message Notifications"),
        help_text=_('Send me an email when new messages arrive.'))
    mail_on_collaborate = models.BooleanField(
        default=True,
        verbose_name=_("Notifications on Collaborations"),
        help_text=_('Inform me when routes or walls change where I am involved.'))

    @property
    def unread_messages(self):
        return self.user.status_set.aggregate(models.Sum('new_msg_count'))['new_msg_count__sum']

    def medium_url(self):
        if self.avatar:
            if os.path.exists(self.medium_path()):
                cb = md5sum_file(self.medium_path())
            else:
                cb = str(time.time())
            return os.path.join(settings.MEDIA_URL, USERS_BASE_FOLDER, str(self.user.pk), AVATAR_FOLDER,
                                AVATAR_MEDIUM + AVATAR_FILE_ENDING + "?cb=" + cb)
        else:
            return static("topo/img/avatar/medium_default.png")

    def thumb_url(self):
        if self.avatar:
            if os.path.exists(self.medium_path()):
                cb = md5sum_file(self.thumb_path())
            else:
                cb = str(time.time())
            return os.path.join(settings.MEDIA_URL, USERS_BASE_FOLDER, str(self.user.pk), AVATAR_FOLDER,
                                AVATAR_THUMB + AVATAR_FILE_ENDING + "?cb=" + cb)
        else:
            return static("topo/img/avatar/thumb_default.png")

    def medium_path(self):
        return os.path.join(settings.MEDIA_ROOT, USERS_BASE_FOLDER, str(self.user.pk), AVATAR_FOLDER,
                            AVATAR_MEDIUM + AVATAR_FILE_ENDING)

    def thumb_path(self):
        return os.path.join(settings.MEDIA_ROOT, USERS_BASE_FOLDER, str(self.user.pk), AVATAR_FOLDER,
                            AVATAR_THUMB + AVATAR_FILE_ENDING)

    def thumbnail(self):
        if self.avatar:
            image = Image.open(os.path.join(settings.MEDIA_ROOT, self.avatar.path))

            image_medium = image.resize((MEDIUM_SIZE, MEDIUM_SIZE), Image.ANTIALIAS)
            medium_path = self.medium_path()
            ensure_dir(medium_path)
            image_medium.save(medium_path)

            image_thumb = image.resize((THUMB_SIZE, THUMB_SIZE), Image.ANTIALIAS)
            thumb_path = self.thumb_path()
            ensure_dir(thumb_path)
            image_thumb.save(thumb_path)

    def change_puzzle_pieces(self, action):
        """Give KPs to user and check if he has enough KP left for the desired action."""
        self.puzzle_pieces = self.puzzle_pieces + get_puzzles(action)
        if self.puzzle_pieces < 0:
            return False
        else:
            self.save()
            return True

    def get_contributed_versions(self, app, model):
        # a queryset of version which the user was involved in
        objtype = ContentType.objects.get(app_label=app, model=model)
        return Version.objects.filter(revision__user=self.user).filter(content_type=objtype)

    def objects_created(self, app, model):
        objtype = ContentType.objects.get(app_label=app, model=model)

        # find all versions of this particular type which contain myself
        contributed_versions = self.get_contributed_versions(app, model)
        contributed_obj_ids = set(contributed_versions.values_list('object_id',
                                                                   flat=True))  # this is a unique set of objects id in which the user was involved

        count = 0
        for object_id in contributed_obj_ids:
            first_version = Version.objects.filter(content_type=objtype).filter(object_id=object_id).order_by(
                '-revision__date_created').first()  # now check if the first version for a particular object is from the user
            if self.user.id == first_version.revision.user.id:
                count += 1
        return count

    @property
    def ascent_count(self):
        return self.user.ascent_set.all().count

    @property
    def edit_count(self):
        return Revision.objects.filter(user=self.user).count()

    @property
    def materials_uploaded(self):
        return self.user.userpic_set.filter(content="info").count()

    @property
    def userpics_uploaded(self):
        return self.user.userpic_set.filter(content="personal").count()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()


@receiver(post_save, sender=User)
def add_default_group_to_user_profile(sender, instance, **kwargs):
    group, group_created = Group.objects.get_or_create(name='Bambino')
    user = instance
    group.user_set.add(user)

users/templates/users/activityfeed.html
{% extends request.is_ajax|yesno:"plain.html,base.html" %}
{% load i18n %}

{% load static %}

{% if not request.is_ajax %}
{# Overwrite title block #}
{% block title %}
    cruxle.org - Activity Feed {{ user.username }}
{% endblock %}
{% endif %}

{% block content %}
  <table class="table table-hover table-responsive table-condensed table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for feed_entry in feed_entries %}
        <tr>
          <td>
            <div class="feed_entry">
              {% if feed_entry.is_ascent %}
                <i class="glyphicon glyphicon-check timeline-item-icon"></i>
              {% endif %}
              <img src="{{ feed_entry.image_url }}" alt=""/>
              <span class="feed_entry-date">{{ feed_entry.date }}</span>,
              <span class="feed_entry-activity">{{ feed_entry.activity }} </span>
              <a href="{{ feed_entry.link }}"><span class="feed_entry-title">{{ feed_entry.object_title }}</span>
              </a>
              <span class="feed_entry-text">{{ feed_entry.text|safe }}</span>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

users/templates/users/ascents_sunburst_graph.html
{% load i18n %}

<!--pre id="data_dump"></pre-->

<div id="ascent_sunburst_chart" style="width:100%; height:400px"><svg></svg></div>

<script type="text/javascript">

var div_id = '#ascent_sunburst_chart';
var url = "{% url 'users:rest_user_ascents' user_id=user.id %}";
var trans = {
    'Routes': '{% trans 'Routes'|truncatechars:14 %}',
    'Ascents': '{% trans 'Ascents'|truncatechars:14 %}',
    'nodata': '{% trans 'No Data Available' %}'
}

ascent_sunburst_chart(div_id, url, trans);

</script>

users/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}

{% load static %}

{# Overwrite title block #}
{% block title %}
    cruxle.org - {{ user.username }}
{% endblock %}
{% block extra_assets %}
{% endblock %}


{% block content %}
{{navtab_entry}}
<div id="user-detail-container" class="col-xs-12 col-lg-8">
  <h4 title="#User{{ user.pk }}"><span class="glyphicon glyphicon-user"></span> {{ user }}
    {% if user == request.user %}
      <a href="{% url "users:profile" %}" title="{% trans "Edit Profile" %}"><span class="glyphicon glyphicon-pencil"></span></a>
    {% else %}
      <a href="{% url "postbox:send_message" user_id=user.pk %}?next={{request.path}}" title="{% trans "Send Message" %}"><span class="glyphicon glyphicon-envelope"></span></a>
    {% endif %}
  </h4>

  <div id="user_profile_navbar">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link"
           data-toggle="tab"
           role="tab"
           href="#user_details"
           data-toggle="tooltip"
           title="{% trans 'Info' %}">
          <span class="fa fa-info-circle fa-lg"></span>
        </a>
      </li>

      <li class="nav-item">
        <a id="user_ascents_navbtn"
           class="nav-link"
           data-toggle="tab"
           role="tab"
           href="#ascent_list"
           data-toggle="tooltip"
           title="{% trans 'Ascents' %}">
          <span class="fa fa-check-square fa-lg"></span>
        </a>
      </li>

      <li class="nav-item">
        <a id="user_graph_navbtn"
           class="nav-link"
           data-toggle="tab"
           role="tab"
           href="#user_graphs"
           data-toggle="tooltip"
           title="{% trans 'Graphs' %}">
          <span class="fa fa-chart-bar fa-lg"></span>
        </a>
      </li>

      <li class="nav-item">
        <a id="activityfeed_navbtn"
           class="nav-link"
           data-toggle="tab"
           role="tab"
           href="#activityfeed"
           data-toggle="tooltip"
           title="{% trans 'Activity Feed' %}">
          <span class="fa fa-history fa-lg"></span>
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane activityfeed-user-details" id="user_details" role="tabpanel">
        <div class="row">
          <div class="col-xs-12 col-md-3">
            {% if user.userprofile.avatar %}
              <img class="profile-avatar" src="{{ user.userprofile.medium_url }}"/>
            {% else %}
              <img class="profile-avatar" src="{% static "topo/img/avatar/medium_default.png" %}"/>
            {% endif %}
          </div>

          <div class="col-xs-12 col-md-9">
            <table class="table table-condensed table-striped">
              <caption>{% trans "Profile" %}</caption>
              <tbody>
              <tr>
                <td>
                  {% trans "Username" %}:
                </td>
                <td>
                  {{ user.username }}
                </td>
              </tr>
              {% if user == request.user %}
              <tr>
                <td>
                  {% trans "Email (only visible to you)" %}:
                </td>
                <td>
                  {{ request.user.email }}
                </td>
              </tr>
              {% endif %}
              <tr>
                <td>
                  {% trans "Language" %}:
                </td>
                <td>
                  {{ LANGUAGE_CODE }}
                </td>
              </tr>
              </tbody>
            </table>

          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <table class="table table-condensed table-striped">
              <caption>{% trans "Info" %}</caption>
              <tbody>
                <tr>
                  <td>{% trans "Puzzlepieces" %}</td>
                  <td>
                    <span class="fa fa-puzzle-piece fa-lg"></span> {{ user.userprofile.puzzle_pieces }}
                  </td>
                </tr>
                <tr>
                  <td>{% trans "Ascents" %}</td>
                  <td>
                    <span class="fa fa-long-arrow-alt-up fa-lg"></span> {{ user.userprofile.ascent_count }}
                  </td>
                </tr>
                <tr>
                  <td>{% trans "Edits" %}</td>
                  <td>
                    <span class="far fa-edit fa-lg"></span> {{ user.userprofile.edit_count }}
                  </td>
                </tr>
                <tr>
                  <td>{% trans "Member since" %}</td>
                  <td>
                    {{ user.date_joined }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="col-xs-12 col-md-6">
            <table class="table table-condensed table-striped">
              <caption>{% trans "Contributions" %}</caption>
              <tbody>
                <tr>
                  <td>{% trans "Walls created" %}</td>
                  <td>
                    {{ user.walls_created_by_me.count }}
                  </td>
                </tr>
                <tr>
                  <td>{% trans "Routes created" %}</td>
                  <td>
                    {{ user.routes_created_by_me.count }}
                  </td>
                </tr>
                <tr>
                  <td>{% trans "Materials uploaded" %}</td>
                  <td>
                    {{ user.userprofile.materials_uploaded }}
                  </td>
                </tr>
                <tr>
                  <td>{% trans "Userpics uploaded" %}</td>
                  <td>
                    {{ user.userprofile.userpics_uploaded }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

        </div> <!-- row -->
      </div> <!-- user_details -->


      <div class="tab-pane activityfeed" id="activityfeed" role="tabpanel">
        <div id="user_activityfeed_content"></div>
      </div> <!-- activityfeed -->


      <div class="tab-pane" id="ascent_list" role="tabpanel">
        <div id="user_ascents_content"><span id="user_ascents_content_spinner" class="fa fa-spinner fa-4x"></span></div>
      </div> <!-- ascent_list -->


      <div class="tab-pane" id="user_graphs" role="tabpanel">
        <div id="user_graphs_content"><span id="user_graphs_content_spinner" class="fa fa-spinner fa-4x"></span></div>

      </div> <!-- user_graphs -->


    </div> <!-- tab content -->
  </div> <!-- user_profile_navbar -->
</div> <!-- user-detail-container -->

<script>
var timeline = new TimelineApi('#user_activityfeed_content', '{% url "users:rest_user_activities" user_id=user.id %}',
        {dump_data: false},
        {
            ticked: "{% trans "ticked" %}",
            edited: "{% trans "edited" %}",
            rated: "{% trans "rated" %}",
            empty: "{% trans "No items to display." %}",
            more: "{% trans "Show More" %}"
        });

$("#activityfeed_navbtn").one("click", function() {
    timeline.renderMore();
});

$("#user_ascents_navbtn").one('click',function() {
    try {
        document.getElementById("user_ascents_content_spinner").classList.add("fa-spin");
    } catch (err) {}
    $("#user_ascents_content").load("{% url "users:user_ascents" user_id=user.id %}");
});

$("#user_graph_navbtn").one("click", function() {
    try {
        document.getElementById("user_graphs_content_spinner").classList.add("fa-spin");
    } catch (err) {}
    $("#user_graphs_content").load("{% url "users:user_route_histogram" user_id=user.id %}");
});

// Javascript to enable link to tab
var prefix = "navtab=";
{% if navtab %}
if (! document.location.hash) { // only use django-view navtab info if no hash is available
        document.location.hash = prefix+"{{navtab}}";
}
{% endif %}

var hash = document.location.hash;
if (! document.location.hash) { // default navtab is info tab
        document.location.hash = prefix+'user_details';
}
$('.nav-tabs a[href="'+hash.replace(prefix,"")+'"]').click();

// Change hash for page-reload
$('.nav-tabs a').on('shown.bs.tab', function (e) {
    window.location.hash = e.target.hash.replace("#", "#" + prefix);
});


window.onhashchange = function() {
    var hash = document.location.hash;
    $('.nav-tabs a[href="'+hash.replace(prefix,"")+'"]').click();
}
</script>

{% endblock %}