micomments/urls.py
from django.conf.urls import *

from micomments import views

app_name = 'micomments'

urlpatterns = [
    url(r'^show/(?P<thread_id>[0-9a-zA-Z]+)', views.comments, name='show'),
    url(r'^add/(?P<thread_id>[0-9a-zA-Z]+)', views.add, name='add'),
    url(r'^delete/(?P<comment_id>\d+)', views.delete, name='delete'),
    url(r'^views/full/(?P<thread_id>[0-9a-zA-Z]*)', views.full, name='views_full'),
    url(r'^views/full/', views.full, name='views_full'),
]

mitopo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import *
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from rest_framework_swagger.views import get_swagger_view

from mitopo.views import schema_view, greeter_index

app_name = 'mitopo'

urlpatterns = [
    path(r'robots.txt', TemplateView.as_view(template_name='mitopo/robots.txt', content_type='text/plain')),
    path(r'admin/', admin.site.urls),
    path("soc/", include("social_django.urls", namespace="social")),
    path(r'i18n/', include('django.conf.urls.i18n')),
    path(r'micomments/', include('micomments.urls')),
    path(r'upload/', include('django_file_form.urls')),
    url(r'apidoc/', schema_view)
]

urlpatterns += i18n_patterns(
    path('', greeter_index, name='greeter_index'),
    path('miroutes/', include('miroutes.urls')),
    path('edit_spot/', include('edit_spot.urls')),
    path('generic_markers/', include('generic_markers.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('stitcher/', include('stitcher.urls')),
    path('micontactform/', include('micontactform.urls')),
    path('miexport/', include('miexport.urls')),
    path('postbox/', include('postbox.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

)

# if in debug mode, redirect static requests to media_ROOT
from django.conf import settings
from  django.views import static

if settings.DEBUG == True:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', static.serve, {
            'document_root': settings.STATIC_ROOT,
        }), ]

users/urls.py
from django.conf.urls import *
from django.contrib.auth.views import LoginView, LogoutView

from users import views
from users import classviews

from django.http import HttpResponse
do_nothing = lambda *args, **kwargs: HttpResponse()

app_name='users'

urlpatterns = [
    url(r'^profile', views.profile, name='profile'),
    url(r'^activityfeed/(?P<user_id>\d+)', views.activityfeed, name='activityfeed'),
    url(r'^activityfeed', views.activityfeed, name='activityfeed'),

    url(r'^user_detail/(?P<user_id>\d+)$', views.user_detail, name='user_detail'),
    url(r'^user_detail/$', views.user_detail, name='user_detail_ajaxstub'),

    url(r'^change_password$', views.change_password, name='change_password'),
    url(r'^change_email$', views.change_email, name='change_email'),
    url(r'^reset_password$', views.reset_password, name='reset_password'),

    url(r'^user_ascents/(?P<user_id>\d+)$', views.user_ascents, name='user_ascents'),
    url(r'^upload_avatar$', views.upload_avatar, name='upload_avatar'),
    url(r'^delete_avatar$', views.delete_avatar, name='delete_avatar'),
    url(r'^register$', views.register, name='users.views.register'),
    url(r'^confirm/(?P<activation_key>.*)$', views.confirm, name='confirm'),
    url(r'^confirm_mail/(?P<activation_key>.*)$', views.confirm_email_change, name='confirm_email_change'),
    url(r'^login$',  LoginView.as_view(), name='django.contrib.auth.views.login'),
    url(r'^logout$', LogoutView.as_view(), name='django.contrib.auth.views.logout'),
    url(r'^route_histogram/(?P<user_id>\d+)$', views.user_route_histogram, name='user_route_histogram'),
    url(r'^test_confirmation$', views.test_confirmation, name='test_confirmation'),
    url(r'^test_message$', views.test_message, name='test_message'),
    url(r'^test_deletion$', views.test_deletion, name='test_deletion'),
    url(r'^test_success$', views.test_success, name='test_success'),

    url(r'^delete_user$', views.delete_user, name='delete_user'),

    url(r'^rest/revisions/(?P<user_id>\d+)$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/revisions$', classviews.RestRevisions.as_view(), name='rest_revisions'),
    url(r'^rest/activities/(?P<user_id>\d+)$', classviews.RestUserActivities.as_view(), name='rest_user_activities'),
    url(r'^rest/ascents/(?P<user_id>\d+)$', classviews.RestUserAscents.as_view(), name='rest_user_ascents'),

    url(r'^rest/routework$', classviews.RouteWork.as_view(), name='rest_routework'),
    url(r'^rest/wallwork$', classviews.WallWork.as_view(), name='rest_wallwork'),
    url(r'^rest/tilerwork$', classviews.TilerWork.as_view(), name='rest_tilerwork'),
    url(r'^rest/panostitcherwork$', classviews.PanoStitcherWork.as_view(), name='rest_panostitcherwork'),

#    url(r'^rest/favroutes$', classviews.FavRoutes.as_view(), name='rest_favroutes'),
    url(r'^rest/favwalls$', classviews.FavWalls.as_view(), name='rest_favwalls'),

    url(r'^user_work/$', views.user_work, name='user_work'),
    url(r'^favourites/$', views.favourites, name='favourites'),
]

micomments/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    threadId = models.CharField(max_length=100, db_index=True)
    comment = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)

micomments/views.py
import html
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render

from micomments.models import Comment

from django.shortcuts import get_object_or_404
from miroutes.utils import replace_objs

def jsonifyComment(comment):
    txt = html.escape(comment.comment, quote=False)
    txt = replace_objs(txt, html=True, absolute_urls=False)
    return {
        "id": comment.pk,
        "comment": txt,
        "user_id": comment.user.id,
        "user_name": comment.user.username,
        "avatar": comment.user.userprofile.thumb_url(),
        "thread_id": comment.threadId,
        "created": comment.created
    }

def createCommentFromDict(commentDict):
    if "user_id" not in commentDict or "comment" not in commentDict or "thread_id" not in commentDict:
        raise ValueError("missing a value: " + commentDict)
    else:
        comment = Comment()
        comment.user = User.objects.get(id=int(commentDict['user_id']))
        comment.comment = commentDict['comment']
        comment.threadId = commentDict['thread_id']
        return comment


def comments(request, thread_id):
    """
    process search request
    """

    chunk_size = request.GET.get('chunk_size')
    try:
        chunksize = int(chunksize)
        allComments = Comment.objects.filter(threadId=thread_id).order_by('-created')[:chunk_size]
    except:
        allComments = Comment.objects.filter(threadId=thread_id).order_by('-created')

    return JsonResponse({"comments": list(map(jsonifyComment, allComments))})


@login_required
def add(request, thread_id):
    """
    process search request
    """
    if request.method == 'POST':
        user = None

        if request.user.is_authenticated:
            user = request.user
        else:
            return JsonResponse({'message': 'Not authorized', 'success': False}, status=403)

        input = json.loads(request.body)

        input['user_id'] = user.id
        input['thread_id'] = thread_id

        try:
            commentObject = createCommentFromDict(input)
            if commentObject.comment != "":
                try:
                    commentObject.save()
                    return JsonResponse({'message': 'Saved comment', 'success': True}, status = 200)
                except Exception as e:
                    return JsonResponse({'message': f'Could not save comment: {e}', 'success': False}, status=400)
            else:
                return JsonResponse({'message': 'not saving empty comment', 'success': False}, status=400)
        except ValueError as e:
            return JsonResponse({'message': str(e), 'success': False}, status=400)

    else:
        return JsonResponse({'message': 'Invalid http method, only POST allowed', 'success': False}, status=405)

    return JsonResponse({'message': 'Bug encountered, please report this', 'success': False}, status=500)


@login_required
def delete(request, comment_id):
    """
    process search request
    """
    if (request.method == 'GET') or (request.method == 'POST'):
        user = None

        if request.user.is_authenticated:
            user = request.user
            comment = get_object_or_404(Comment, pk=comment_id)
            if comment.user != user:
                return JsonResponse({'message': 'Not authorized', 'success': False}, status=403)
            else:
                try:
                    comment.delete()
                    return JsonResponse({'message': 'Deleted comment', 'success': True}, status=200);
                except Exception as e:
                    return JsonResponse({'message': f'Could not delete comment {comment.pk}: {e}', 'success': False}, status=400)
        else:
            return JsonResponse({'message': 'Not authorized', 'success': False}, status=403)
    else:
        return JsonResponse({'message': 'Invalid http method, only GET OR POST allowed', 'success': False}, status=405)
    return JsonResponse({'message': 'Bug encountered, please report this', 'success': False}, status=500)


def full(request, thread_id):
    chunk_size = request.GET.get('chunk_size')
    return render(request, 'micomments/show_comments.html', {
        'thread_id': thread_id,
        'chunk_size': chunk_size
    })

micomments/templates/micomments/show_comments.html
{# {% include "show_comments.html" with thread_id=1 %} #}

{% load i18n %}
<script>
function format_date(date) {
    return date.toLocaleString(undefined, {
        year: 'numeric',
        weekday: 'short',
        month: 'short',
        day: 'numeric',
        hour: 'numeric',
        minute: 'numeric',
    });
}


function show_comments_{{ thread_id }}(url) {

    var url = url || '{% url 'micomments:show' thread_id=thread_id %}?chunk_size={{ chunk_size }}';

    var csrftoken = $.cookie('csrftoken');
    var delete_baseurl = '{% url 'micomments:delete' comment_id=0 %}';
    delete_baseurl = delete_baseurl.slice(0, -1);
    {% if user.is_authenticated %}
    var my_user_id = parseInt('{{ user.id }}');
    {% else %}
    var my_user_id = undefined;
    {% endif %}
    $.get({
        url: url,
        contentType: 'application/json',
        dataType: 'json',
        success: function (data) {
            var mylist = $('#cl_{{ thread_id }}');
            mylist.html("");
                $.each(data.comments, function (key, value) {

                    var upper_div=$('<div>', {
                        id: 'comment_upper_descr_row',
                        class: 'row'});

                    //add avatar
                    upper_div.append( $('<div>', {
                        class: 'col-xs-3 comment-userprofile-area',
                    })
                    .append( $('<img>', {
                        class: 'comment-avatar',
                        src: value.avatar,
                    }))
                    // add name
                    .append( $('<a>', {
                        href: "{%url 'users:user_detail_ajaxstub' %}" + value.user_id,
                        text: value.user_name,
                    }))
                    );


                    if(my_user_id === value.user_id) {
                        var del_func = 'deleteComment_{{ thread_id }}(\"' + delete_baseurl + value.id + '\")';
                        var edit_div = $('<div>',{
                            class: 'comment-delete pull-right'
                        }).append($('<a>', {
                            href: 'javascript:'+del_func,
                            html: "<span class='fas fa-trash-alt fa-lg btn'></span>",
                        }));
                    }

                    // on the right hand side
                    upper_div.append($('<div>', {
                        class: 'col-xs-9',
                    })
                             .append($('<div>', {
                                 class: 'row',
                             })
                                     .append($('<div>', {
                                         class: 'col-xs-12 comment-date-header-area',
                                     })
                                             // add date
                                             .append($('<span>', {
                                                 class: 'fas fa-calendar-alt text-muted',
                                                 text: ' ' + format_date(new Date(value.created)),
                                             }))
                                             .append(edit_div)
                                            )
                                     //.append($('<hr>'))
                                     .append($('<div>', {
                                         class: 'col-xs-12 comment-textarea',
                                         html: value.comment,
                                     }))
                                    ));

                    var comment_div = $("<li>").append(upper_div);

                    mylist.append(comment_div).append($('<hr>'));
                });
            if($("#cl_{{ thread_id }} li").length == 0){
                mylist.append("<li>{% trans "No comments yet." %}</li>");
            }
            if($("#cl_{{ thread_id }} li").length < {{ chunk_size }}){
                $("#showall_{{ thread_id }}").hide();
                $("#hide_{{ thread_id }}").hide();
            }else if($("#cl_{{ thread_id }} li").length == {{ chunk_size }}){
                $("#showall_{{ thread_id }}").show();
                $("#hide_{{ thread_id }}").hide();
            }else{
                $("#hide_{{ thread_id }}").show();
                $("#showall_{{ thread_id }}").hide();
            }

        }
    });

}

function deleteComment_{{ thread_id }}(delete_url) {
    var csrftoken = $.cookie('csrftoken');
    $.post({
        url: delete_url,
        contentType: 'application/json',
        dataType: 'json',
        beforeSend: function (request) {
            request.setRequestHeader("X-CSRFToken", csrftoken);
        },
        success: function (e) {
            append_message(e.message, 'success');
        },
        error: function (e) {
            append_message(e.responseJSON.message, 'danger');
        },
        complete: function(e) {
            show_comments_{{ thread_id }}();
        }
    });
}

function addComment_{{ thread_id }}() {
    var payload = {
        "comment": $('#textarea_{{ thread_id }}').val()};
    var csrftoken = $.cookie('csrftoken');

    $.post({
        url: '{% url 'micomments:add' thread_id=thread_id %}',
        data: JSON.stringify(payload),
        contentType: 'application/json',
        dataType: 'json',
        beforeSend: function (request) {
            request.setRequestHeader("X-CSRFToken", csrftoken);
        },
        success: function (e) {
            $('#add_error_msg_{{ thread_id }}').hide();
            $('#textarea_{{ thread_id }}').val("");
            show_comments_{{ thread_id }}();
        },
        error: function (e) {
            $('#add_error_msg_{{ thread_id }}_text').text(e.responseJSON.message)
            $('#add_error_msg_{{ thread_id }}').show();
        },
        complete: function(e) {
            show_comments_{{ thread_id }}();
        }
    });
}

show_comments_{{ thread_id }}();
</script>


<ul id="cl_{{ thread_id }}" class="commentlist">
</ul>
<br>
<a id="showall_{{ thread_id}}"
   href="#"
   onclick="show_comments_{{ thread_id }}('{% url 'micomments:show' thread_id=thread_id %}')">
    <span class="far fa-plus-square"></span>
    {% trans "Show All" %}
</a>
<a id="hide_{{ thread_id}}"
   href="#"
   style="display: none;"
   onclick="show_comments_{{ thread_id }}()">
    <span class="far fa-minus-square"></span>
   {% trans "Hide" %}
</a>

<hr>

<div class="row">
    <div class="col-xs-12">
        {% if user.is_authenticated %}
        {% trans "Add comment" %}

        <div class="row comment-box">
            <div class="col-xs-12">
                <textarea id="textarea_{{ thread_id }}" class="comment-input full-width"></textarea>
            </div>
            <div class="col-xs-12">
                  <div id="add_error_msg_{{ thread_id }}"
                       class="alert alert-danger"
                       role='alert'
                       style="display:none;margin-left:0px;">
                  <span class='glyphicon glyphicon-warning-sign'></span>
                  <span id="add_error_msg_{{ thread_id }}_text"></span>
                </div>
                {% if not no_send_button %}
                <a href="#" class="comment-submit btn btn-success top-buffer-margin-half" onclick="addComment_{{ thread_id }}(this)">
                    <span class="fa fa-check"></span>
                    <span class="hidden-sm-down">{% trans "Submit" %}</span>
                </a>


                {% endif %}
                <div class="clearfix"></div>
            </div>
        </div>
        {% else %}
        <div class="comment-box">
            {% url "users:django.contrib.auth.views.login" as login_url %}
            <a href="javascript:(function () {
            $('.modal').modal('hide');
            $('#user-dropdown-menu').addClass('open');
            })();"
               class="btn btn-success"
               tabindex="0"
               role="button"
               data-toggle="popover"
               data-placement="right"
               data-content='{% blocktrans with href=login_url|add:"?next="|add:request.path %}Please <a href="{{ href }}">login</a> to create a comment.{% endblocktrans %}'
               data-trigger="focus">
               <span class="fa fa-plus-circle"></span>
               {% blocktrans with next=request.path %}Create a new comment.{% endblocktrans %}
            </a>
        </div>
        {% endif %}

    </div>
</div>

<script>
prepare_comment_input("textarea_{{ thread_id }}");
</script>